---
title: "City of Rochester"
author: "Ed"
date: "2025-08-06"
output: html_document
---

```{r}

packages <- c(
  'ggplot2', 'corrplot','tidyverse','shiny','shinydashboard','shinycssloaders',
  'bslib','readxl','DT','mlbench','caTools','gridExtra','doParallel','grid',
  'reshape2','caret','tidyr','Matrix','lubridate','plotly','RColorBrewer',
  'data.table','scales','rfm','forecast','TTR','xts','dplyr', 'treemapify','leaflet'
)
for (package in packages) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

```

# Load data
```{r}
parks <- read_csv("Parks_and_Playgrounds.csv")
tree <- read_csv("Trees.csv")
tree_address <- read_csv("Trees_address.csv")
```
```{r}
tree_temp <- inner_join(tree, tree_address,by="PARKS_VAL") %>%
  select(FULLADDR,GENUS,SPECIES,TREE_NAME_VAL,THEME_VAL,MAINT_VAL,AREA_VAL) %>%
  na.omit() %>%
  unique()

tree_df <- inner_join(tree_temp,parks,by="FULLADDR",relationship = "many-to-many") %>%
  select(FULLADDR,NAME,PHONE,AGENCYURL,EMAIL,Longitude,Latitude,GENUS,SPECIES,TREE_NAME_VAL,THEME_VAL,MAINT_VAL,AREA_VAL) %>%
  na.omit() %>%
  unique()
```


```{r}
## Tree Inventory Over Time (Cumulative Line Plot) 
tree$new_inv_date <- lubridate::year(as.Date(tree$INV_DATE, format =  "%Y/%m/%d"))

```
```{r}
  tree_diameter <- tree %>%
    summarise(Total = mean(DBH_VAL_update)) %>%
```


```{r}
  g <- tree %>%
    group_by(new_inv_date) %>%
    summarise(Total = n()) %>%
    filter(new_inv_date >= '2008') %>%
    select(new_inv_date, Total) %>% 
    ggplot(aes(x =new_inv_date ,y = Total))  +
    geom_bar(stat = "identity",width = 0.5, fill='black') +
    labs(x ="Inventory Year", y = "Total") 
  theme(legend.text = element_text(size = 10),
        legend.title = element_text(size = 10),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10))
  
  ggplotly(g)

```

```{r}
 g <- tree %>%
    group_by(GENUS) %>%
    summarise(Total = n()) %>%
    select(GENUS, Total) %>% 
    arrange(desc(Total),by_group = FALSE) %>%
    top_n(n = 10)
g
```

# combine trees and tree address
```{r}
tree_temp <- inner_join(tree, tree_address,by="PARKS_VAL") %>%
  select(FULLADDR,GENUS,SPECIES,TREE_NAME_VAL,THEME_VAL,MAINT_VAL,AREA_VAL) %>%
  na.omit() %>%
  unique() #


  

```

```{r}
tree_temp2 <- inner_join(tree_temp,parks,by="FULLADDR",relationship = "many-to-many") %>%
  select(FULLADDR,NAME,PHONE,AGENCYURL,EMAIL,Longitude,Latitude,GENUS,SPECIES,TREE_NAME_VAL,THEME_VAL,MAINT_VAL,AREA_VAL) %>%
  na.omit() %>%
  unique()
```
```{r}
library(stringr)
tree$DBH_VAL_update <- as.numeric(str_remove_all(tree$DBH_VAL, "[\"']"))
```
```{r}
 


format(round(tree_diameter<- mean(tree$DBH_VAL_update, na.rm = TRUE), 2), nsmall = 2)
```
```{r}
g_df <- tree %>%
    group_by(GENUS) %>%
    summarise(Total = n()) %>%
    select(GENUS, Total) %>% 
    arrange(desc(Total)) %>%
    top_n(n = 10)
  
  g <- tree %>%
    filter(GENUS %in% c(g_df$GENUS)) %>%
    group_by(GENUS) %>%
    summarise(Total = mean(DBH_VAL_update)) %>%
    select(GENUS, Total)
  
  g
```


```{r}
```

